<?php
$enableSocial = true;
?>

<?php if ($enableSocial && $block->getProductData()->getProductUrl() !== ''): ?>
    <?php
    $popupSetting = 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=450,width=600';
    $link = urlencode($block->getProductData()->getProductUrl());
    $name = $block->getProductData()->getName();
    $image = $block->getUrl('pub/media/catalog').'product'.$block->getProductData()->getImage();
    ?>

    <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $link; ?>&t=<?php echo $name; ?>"
       onclick="window.open(this.href, '', '<?php echo $popupSetting; ?>');return false;"
       target="_blank" title="Share on Facebook">Facebook
    </a>

    <a href="https://pinterest.com/pin/create/button/?url=<?php echo $link; ?>&media=<?php echo $image; ?>&description=<?php echo $name; ?>"
       onclick="window.open(this.href, '', '<?php echo $popupSetting; ?>');return false;"
       target="_blank" title="Pin it">Pinterest
    </a>

    <a href="http://twitter.com/home/?status=<?php echo $name . ' - ' . $link; ?>"
       onclick="window.open(this.href, '', '<?php echo $popupSetting; ?>');return false;"
       target="_blank" title="Twitter">Twitter
    </a>

<?php endif; ?>



